/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.barangControl;
import com.sun.xml.internal.ws.handler.HandlerException;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.util.*;

public class barang_view extends javax.swing.JFrame {
//    private controller.barangControl controller_barang;

    public barang_view(){
        initComponents();
        myInitComponents();
//        controller_barang.kosongkanForm();
//        controller_barang.TampilData();
    }
    
    public void myInitComponents(){
        welcome.setForeground(Color.white);
        label_tabelbarang.setForeground(Color.white);
        label_idbarang.setForeground(Color.white);
        label_namabarang.setForeground(Color.white);
        label_satuanbarang.setForeground(Color.white);
        label_hargabarang.setForeground(Color.white);
        label_stokbarang.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        welcome = new javax.swing.JLabel();
        label_tabelbarang = new javax.swing.JLabel();
        label_idbarang = new javax.swing.JLabel();
        input_idbarang = new javax.swing.JTextField();
        input_namabarang = new javax.swing.JTextField();
        label_namabarang = new javax.swing.JLabel();
        label_satuanbarang = new javax.swing.JLabel();
        input_satuan = new javax.swing.JTextField();
        label_stokbarang = new javax.swing.JLabel();
        input_stok = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        input_harga = new javax.swing.JTextField();
        label_hargabarang = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        welcome.setText("APLIKASI GROSIR");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 29, -1, -1));

        label_tabelbarang.setBackground(new java.awt.Color(255, 255, 255));
        label_tabelbarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label_tabelbarang.setText("- TABEL BARANG -");
        getContentPane().add(label_tabelbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 82, -1, -1));

        label_idbarang.setText("ID BARANG");
        getContentPane().add(label_idbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 150, -1, -1));

        input_idbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_idbarangActionPerformed(evt);
            }
        });
        getContentPane().add(input_idbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 148, 253, -1));
        getContentPane().add(input_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 185, 253, -1));

        label_namabarang.setText("NAMA BARANG");
        getContentPane().add(label_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 187, -1, -1));

        label_satuanbarang.setText("SATUAN");
        getContentPane().add(label_satuanbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 224, -1, -1));
        getContentPane().add(input_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 222, 253, -1));

        label_stokbarang.setText("STOK");
        getContentPane().add(label_stokbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 298, -1, -1));
        getContentPane().add(input_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 296, 253, -1));

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 357, -1, -1));

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 357, -1, -1));

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 357, 78, -1));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 393, 78, -1));

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 393, 72, -1));

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 393, -1, -1));

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelBarang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 148, 480, 248));
        getContentPane().add(input_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 259, 253, -1));

        label_hargabarang.setText("HARGA");
        getContentPane().add(label_hargabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 261, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\store 50.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed

    }//GEN-LAST:event_kembaliActionPerformed

    private void input_idbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_idbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_idbarangActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelBarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton edit;
    public javax.swing.JButton hapus;
    public javax.swing.JTextField input_harga;
    public javax.swing.JTextField input_idbarang;
    public javax.swing.JTextField input_namabarang;
    public javax.swing.JTextField input_satuan;
    public javax.swing.JTextField input_stok;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton kembali;
    private javax.swing.JLabel label_hargabarang;
    private javax.swing.JLabel label_idbarang;
    private javax.swing.JLabel label_namabarang;
    private javax.swing.JLabel label_satuanbarang;
    private javax.swing.JLabel label_stokbarang;
    private javax.swing.JLabel label_tabelbarang;
    public javax.swing.JButton reset;
    public javax.swing.JButton simpan;
    public javax.swing.JTable tabelBarang;
    public javax.swing.JButton tambah;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
