/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class home_view extends javax.swing.JFrame {

    
    
    public home_view() {
        initComponents();
        myInitComponents();
    }

    public void myInitComponents(){
        welcome.setForeground(Color.white);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        welcome = new javax.swing.JLabel();
        buttonBarang = new javax.swing.JButton();
        buttonCustomer = new javax.swing.JButton();
        buttonSupplier = new javax.swing.JButton();
        buttonJual = new javax.swing.JButton();
        buttonBeli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 550));
        setPreferredSize(new java.awt.Dimension(920, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        welcome.setText("APLIKASI GROSIR");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        buttonBarang.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonBarang.setText("BARANG");
        buttonBarang.setBorderPainted(false);
        buttonBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarangActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 115, 44));

        buttonCustomer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonCustomer.setText("CUSTOMER");
        buttonCustomer.setBorderPainted(false);
        buttonCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 116, 44));

        buttonSupplier.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonSupplier.setText("SUPPLIER");
        buttonSupplier.setBorderPainted(false);
        buttonSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 115, 44));

        buttonJual.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonJual.setText("JUAL");
        buttonJual.setBorderPainted(false);
        buttonJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJualActionPerformed(evt);
            }
        });
        getContentPane().add(buttonJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 115, 44));

        buttonBeli.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonBeli.setText("BELI");
        buttonBeli.setBorderPainted(false);
        buttonBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 115, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\store 50.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //tombol barang
    private void buttonBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarangActionPerformed
//        new barang_view().setVisible(true);
//        dispose();
    }//GEN-LAST:event_buttonBarangActionPerformed

    //tombol customer
    private void buttonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerActionPerformed
//        new customer_view().setVisible(true);
//        dispose();
    }//GEN-LAST:event_buttonCustomerActionPerformed

    //tombol supplier
    private void buttonSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupplierActionPerformed
//        new supplier_view().setVisible(true);
//        dispose();
    }//GEN-LAST:event_buttonSupplierActionPerformed

    //tombol jual
    private void buttonJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJualActionPerformed
//        new jual_view().setVisible(true);
//        dispose();
    }//GEN-LAST:event_buttonJualActionPerformed

    //tombol beli
    private void buttonBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeliActionPerformed
//        new beli_view().setVisible(true);
//        dispose();
    }//GEN-LAST:event_buttonBeliActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonBarang;
    public javax.swing.JButton buttonBeli;
    public javax.swing.JButton buttonCustomer;
    public javax.swing.JButton buttonJual;
    public javax.swing.JButton buttonSupplier;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
